version: '3.7'

services:
    postgresql:
        container_name: 'CHERRY'
        image: 'bitnami/postgresql:12'
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=cherry
            - POSTGRESQL_DATABASE=cherry
